### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by driss-chelouati** [kiosion/vite-plugin-class-mangler#1]
Trying to install this package with 

```
yarn add -D vite-plugin-class-mangler
```

results in

```
error An unexpected error occurred: "https://registry.yarnpkg.com/vite-plugin-class-mangler: Not found".
```

**Comment by kiosion** [comment]
There isn't a version on NPM yet as it's not fully functional; I'll remove that from the readme for now to avoid confusion

**Comment by driss-chelouati** [comment]
Got it. Adding it as a dependency in my project for now, so I can test it on HTML files.

**Comment by kiosion** [comment]
Hm not sure if it'll work, I've only messed around with Svelte as of now, and even that's pretty spotty in terms of working consistently. Hopefully I'll have some more free time later this month to look into working on this again though^^
